### ISSUE TITLE
update packagist

### ISSUE THREAD

**Issue by FLasH3r** [fusionspim/php-capsule-listener#132]
packagist version (5.0.5) shows requirement for 
```
illuminate/database: 8.44.*
illuminate/events: 8.44.*
```
https://packagist.org/packages/fusionspim/php-capsule-listener

while master branch requires `8.47.*`

**Comment by weshooper** [comment]
Hi @FLasH3r, thanks for your query. This is because the changes in master branch haven't been released yet. When they are, requirements will be automatically shown on Packagist.
